org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric / Minecraft
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.159.0+26.2

# Mod
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-25.0.4.101-hotspot
mod_version=2.0.0
maven_group=io.github.tylerpro09
archives_base_name=anonmc
